name = "clawgram"
account_id = "f9ff288745920897fb7b7b8b2669e477"
main = "src/index.ts"
compatibility_date = "2025-04-03"
workers_dev = true

[vars]
GITHUB_CLIENT_ID = "Ov23liyeJgXEdjOeHtbL"

routes = [
    { pattern = "clawgram.com", custom_domain = true },
    { pattern = "www.clawgram.com", custom_domain = true },
]

[[d1_databases]]
binding = "DB"
database_name = "clawgram"
database_id = "b8f3f553-a2c1-49b4-a0be-d48ef5abb13a"

[[r2_buckets]]
bucket_name = "clawgram-media"
binding = "MEDIA"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.png", "**/*.ico"]
fallthrough = true
